add smoke test & cloud front

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -377,7 +377,51 @@ jobs:
           channel: udapeople-pipe-line-faliure
           event: fail
           ignore_errors: true
-      #- destroy-environment            
+      #- destroy-environment  
+
+  smoke-test:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      # - checkout
+      - run:
+          name: Backend smoking test.
+          command: |
+            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            
+            URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
+            #URL="http://h00a.com"
+            if curl -s --head ${URL}
+            then
+              echo "It worked!"
+              exit 0
+            else
+              echo "Rolling Back"
+              exit 1
+            fi
+      #- notify_on_failure
+      #- destroy_environment
+
+  cloudfront-update:
+    docker:
+      - image: hanyshaker1/aws-and-node
+    steps:
+      - checkout
+      # - run:
+      #     name: Save Old Workflow ID to kvdb.io
+      #     command: |
+      #       export OLD_WORKFLOW_ID=$(aws cloudformation \
+      #                 list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+      #                 --no-paginate --output text)
+      #       echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
+      #       curl -k https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d "${OLD_WORKFLOW_ID}"
+      - run:
+          name: Update cloudfront distribution by new stack
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/cloudfront.yml \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:5}" \
+              --stack-name InitialStack
 
 #   smoke-test:
 #     docker:
@@ -440,32 +484,32 @@ jobs:
 workflows:
   default:
     jobs:
-      - build-frontend
-      - build-backend
-      - test-frontend:
-          requires: [build-frontend]
-      - test-backend:
-          requires: [build-backend]
-      - scan-frontend:
-          requires: [build-frontend]          
-      - scan-backend:
-          requires: [build-backend]
-      - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-          filters:
-            branches:
-             only: [main]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-backend:
-          requires: [run-migrations]
-      - deploy-frontend:
-          requires: [deploy-backend, deploy-infrastructure]      
-      #- smoke-test:
-      #    requires: [deploy-backend, deploy-frontend]
-      #- cloudfront-update:
-      #    requires: [smoke-test]
-      #- cleanup:
-      #    requires: [cloudfront-update]
+      #- build-frontend
+      #- build-backend
+      #- test-frontend:
+      #    requires: [build-frontend]
+      #- test-backend:
+      #    requires: [build-backend]
+      #- scan-frontend:
+      #    requires: [build-frontend]          
+      #- scan-backend:
+      #    requires: [build-backend]
+      #- deploy-infrastructure:
+      #    requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+      #    filters:
+      #      branches:
+      #       only: [main]
+      #- configure-infrastructure:
+      #    requires: [deploy-infrastructure]
+      #- run-migrations:
+      #    requires: [configure-infrastructure]
+      #- deploy-backend:
+      #    requires: [run-migrations]
+      #- deploy-frontend:
+      #    requires: [deploy-backend, deploy-infrastructure]      
+       - smoke-test
+      #     requires: [deploy-backend, deploy-frontend]
+       - cloudfront-update
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
